name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: install pnpm
        run: npm i pnpm@9 -g
      - run:
          - pnpm install
          - pnpm -r build
          - pnpm -r publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
